### PR TITLE
🧵 Fixed datetime is not displayed for Forum thread

### LINKED ISSUE #3347: Creation date and time is not displayed for a Forum Thread
Hello guyz:

I just noticed this possible improvement or addition in Joystream Pioneer.
If you create a new Forum Thread and open it, the date and time of creation of the thread is not shown.
Whereas if you reply on that thread, the date and time of reply thread is shown in the right side.

Please see picture on link below for easy illustration...
https://drive.google.com/file/d/1m9l8nQgA-pHohckhKUT8eqKM9Te-UxlG/view?usp=sharing

I suggest Joystream Pioneer be improved by adding creation date and time of a forum thread.
Possibly on upper right side of the thread same with reply.

Thank you

### PR DESCRIPTION
**Pull request by mkbeefcake**
Fixes #3347

### CODE REVIEW

**Comment by freakstatic** [comment]
@mkbeefcake thanks for the PR! :+1:

**Review by thesan — COMMENTED** [review]
Thank you for the PR. This is a clever solution unfortunately the design requires to show the block number (plus we are planning to link these to the polkadot block explorer in the future). Therefore showing block 0 is not acceptable. However this information is available for example in the result of this graphqQl query:
```gql
query {
  forumPosts (where: { thread: { id_eq: "470" } }) {
    forumthreadinitialPost {
      createdInEvent {
        inBlock
      }
    }
    postaddedeventpost {
      inBlock
    }
    text
  }
}
```
Which correspond to this thread: https://dao-git-fork-mkbeefcake-fix-datetime-nodisp-fo-5cfa44-joystream.vercel.app/#/forum/thread/470

So by changing the fragment in `packages/ui/src/forum/queries/forum.graphql`

**Review by thesan — CHANGES_REQUESTED** [review]
:point_up:

**Comment by mkbeefcake** [comment]
Thanks for your detailed information. I will check around and fix this issue.

**Comment by mkbeefcake** [comment]
issue_1
Hello thesan

I have one thing to discuss with you, I tried to check useForumThreadPosts() in packages/ui/src/forum/hooks/useFormThreadPosts.ts file and added the console.log() function for fetched response (postsResults.data?.forumPosts) via GraphQL.  Here as you can see in the screenshot, it returns "postaddeventpost' field as empty for the first POST item. and the this causes that problem.

so I can guess we have to change the code for adding 'postaddeventpost' field at the first post creation time in thread. also hope to know how to get the block number about this 'empty' field..

**Comment by thesan** [comment]
Hello @mkbeefcake yes you are right that the current query node behaviour is not ideal, `postaddeventpost` shouldn't be empty on the thread post. However this can be worked around with the query I suggested yesterday. Here's the result from the playground:
thread-block

This way both the thread and its replies can be fetched in one query.

**Comment by mkbeefcake** [comment]
Hello thesan

I updated the graphql and changed the source code. please review it again

**Review by thesan — APPROVED** [review]
Perfect ! Thank you for your work :pray:

**Pull request merged**
