### PR TITLE
🧑‍🏭 Maintenance screen

### PR DESCRIPTION
**Pull request by WRadoslaw**
- #3636

### CODE REVIEW

**Comment by dmtrjsg** [comment]
@thesan to add how to invoke this screen to the admin docs.

**Comment by dmtrjsg** [comment]
@WRadoslaw will add the screen to the story book.

**Review by thesan — CHANGES_REQUESTED** [review]
It's just a small detail but it's weird to have this story out of the menu by itself

**Review by thesan — CHANGES_REQUESTED** [review]
Just updating the doc...

**Review by thesan — APPROVED** [review]
All good now :+1:

**Pull request merged**
