### PR TITLE
🥑 Apply filters to past proposals

### LINKED ISSUE #586: Apply filters to the past proposal list

### PR DESCRIPTION
**Pull request by p-sad**
Closes #586 
Filters work well with past proposals at the moment. Their behaviour for active proposals is currently undefined, but by design they aren't meant to used with Active ones. The only filter that would cause problems with active proposals would be the lifetime filter since active proposals don't have an end date.
Lifetime filter has been tested for start date only/end date only, as we don't have an OR clause resolver in our mocks. The intervals used are correct in theory however.

### CODE REVIEW

**Comment by jodator** [comment]
> Filters work well with past proposals at the moment.

And it should be only for the past ones :+1:

**Review by DevNikita16 — CHANGES_REQUESTED** [review]
Everything works well 👍 But you should provide proper text for select in types/stages

**Comment by p-sad** [comment]
@DevNikita16 As in, a text filter for narrowing down the selection in the dropdown? That's not a bad idea, but I'd add it as a follow-up PR. I didn't even touch those components in this one

**Comment by p-sad** [comment]
Added as issue #1103, will do right after I'm done with current task

**Comment by DevNikita16** [comment]
I meant that the words here should be separated by space, you should use `camelCaseToText`
image

**Comment by jodator** [comment]
> I meant that the words here(and in stages) should be separated by space, you should use `camelCaseToText`

This might be done together with #1103 if @p-sad didn't touch them yet and the plan is to do it in #1103.

**Comment by p-sad** [comment]
Updated issue to include replacing camelCase with spaces

**Review by DevNikita16 — APPROVED** [review]

**Pull request merged**
