### PR TITLE
VoteForCouncil: Fix use total balance

### PR DESCRIPTION
**Pull request by traumschule**
This correctly shows and uses total balance for accounts when voting.

### CODE REVIEW

**Comment by freakstatic** [comment]
LGTM!

**Comment by freakstatic** [comment]
Before:
image
After:
image

**Review by freakstatic — APPROVED** [review]

**Comment by WRadoslaw** [comment]
@traumschule Hey, good PR! Could I ask you for one thing? Since the PR basically takes on #3869 problem, it would be awesome if you could extend the solution to cover the scope of this issue.

**Comment by traumschule** [comment]
Checked again and am not sure if this wasn't fixed in #3817 already. Please help me find the file, grep let me down this time.

**Comment by WRadoslaw** [comment]
Looks like #3817 was overwritten by #3794. 

@dmtrjsg question is whether `Selected amount exceeds account balance.` as validation message is good as well

**Review by WRadoslaw — APPROVED** [review]

**Pull request merged**
