### PR TITLE
Markdown Support: Use RemarkGFM to support additional syntax.

### LINKED ISSUE #2425: Posts with bullet points sometimes include a ">" character
- [ ] Fix alignment of Bullet points and show them as dots.

This uses external lib (ck editor) we want to add a fix on our end **(upd REAct markdown)** as opposed to tempering with the ck editor lib.

@Dev ⚠️  do not spend more than 3 SP on this. Speak to WGl and @thesan if this turns to be harder than expected.

______
**Taken at**: https://pioneer-2.vercel.app/#/forum/thread/1
**Fields**:
- Houston, we have a problem.: Forum: posts with bullet points sometimes include a &gt; character
- Give us some details: Forum: posts with bullet points sometimes include a &gt; character
- Forum: posts with bullet points sometimes include a &gt; character
- Discrod Handle: tomato#9464

SCREENSHOT
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/100b6e50-597b-46ca-833c-b41f482713c4-annotated_91ae9694-42bd-4b69-918f-42b482f56cc4.png?etag=d59a40e8aa924c3399aeb4306988372b)*

**Browser**: Chrome 98 (Windows 10)
**Screen size**: 3440x1440
**Browser size**: 1718x1306
**[Open #53 in Usersnap](https://app.usersnap.com/l/feedback/8dda6c94-5a20-45b0-8a0b-29e3af44a786?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

### PR DESCRIPTION
**Pull request by oleksanderkorn**
https://pioneer-2-git-fork-oleksanderkorn-bugfix-2712-gfm-joystream.vercel.app/#/forum/thread/174:
image

https://pioneer-2-git-fork-oleksanderkorn-bugfix-2712-gfm-joystream.vercel.app/#/proposals/preview/165?post=187:
image

Closes #2425

### CODE REVIEW

**Comment by traumschule** [comment]
[looks](https://dao-git-fork-oleksanderkorn-bugfix-2712-gfm-joystream.vercel.app/#/forum/thread/185) much better already. did you have any luck with tables yet?
forum-table

**Comment by oleksanderkorn** [comment]
> [looks](https://dao-git-fork-oleksanderkorn-bugfix-2712-gfm-joystream.vercel.app/#/forum/thread/185) much better already. did you have any luck with tables yet?
> 
> forum-table
> 
> 

There is a table actually in my example. Although some of them are not rendered(for example yours), not sure what is the reason for that 🤔

**Comment by traumschule** [comment]
was because copy-paste from a former post adds extra newlines, looks ok for this one

forum-table

just needs a little css magic to look like on GH

| WG | Weight | Planned Increase | Lead | Start Budget (M tJOY) |
| --- | --- | --- | --- | --- |
| Builders | 8 | 12 | 1.4 | 27.63 |
| Content | 5 | 4 | 0.2 | 5.96 |
| Distribution | 6 | 8 | 1.7 | 3.77 |
| Forum | 1 | 1 | 0.2 | 1.83 |
| HR | 8 | 14 | 1.8 | 17.30 |
| Marketing | 2 | 7 | 1.5 | 3.12 |
| Storage | 6 | 10 | 1.8 | 0 |
| Total | | 56 | 10.4 | 59.61 |

**Comment by oleksanderkorn** [comment]
> was because copy-paste from notion adds extra newlines, looks ok for this one
> 
> forum-table
> 
> just needs a little css magic to look like on GH
> 
> WG	Weight	Planned Increase	Lead	Start Budget (M tJOY)
> Builders	8	12	1.4	27.63
> Content	5	4	0.2	5.96
> Distribution	6	8	1.7	3.77
> Forum	1	1	0.2	1.83
> HR	8	14	1.8	17.30
> Marketing	2	7	1.5	3.12
> Storage	6	10	1.8	0
> Total		56	10.4	59.61

Added some styling:

image

**Comment by oleksanderkorn** [comment]
@thesan please review

**Review by thesan — APPROVED** [review]
Nice :heart_eyes: ! It looks really good !
Plus it also solves #2425 :+1:

**Pull request merged**
