### PR TITLE
Remove scroll when it's not needed

### PR DESCRIPTION
**Pull request by 0xPhoenixeth**
fix

### CODE REVIEW

**Review by traumschule — APPROVED** [review]
LGTM, tested with https://dao-git-fix-remove-perma-scroll-joystream.vercel.app/#/proposals/preview/63?post=158

@0xPhoenixeth please add to description: fixes #4187

**Review by gyroflaw — APPROVED** [review]

**Comment by chrlschwb** [comment]
@0xPhoenixeth , fix the conflicts.

**Comment by chrlschwb** [comment]
which issue does this solve?

**Comment by traumschule** [comment]
Seems to be a duplicate to #4270 with a different solution to #4129.

**Pull request closed without merging**
