### PR TITLE
fixes #4170, fixes #3659, fixes #4034

### LINKED ISSUE #3659: The "My profile, Working groups, Proposals and etc" extend beyond the sidebar
The "My profile, Working groups, Proposals, etc." extend beyond the sidebar if I have a large account balance (like Alice)

Alice's account is not hidden
image

Alice's account is hidden
image

### LINKED ISSUE #4034: Regression on WG `History` tab
App crash on `/#/working-groups/storage`
```
react-dom.production.min.js:216 TypeError: Cannot read properties of undefined (reading 'map')
    at useGroupActivities.ts:35:53
    at Object.So [as useMemo] (react-dom.production.min.js:168:377)
    at n.useMemo (react.production.min.js:23:113)
    at n.useGroupActivities (useGroupActivities.ts:21:22)
    at n.HistoryTabSidebar (HistoryTab.tsx:38:26)
```
Edit: only with https://dao-git-fork-mkbeefcake-fix-forumpostreplyntshow4022-joystream.vercel.app/#/working-groups/storage (#4023)

### LINKED ISSUE #4170: [USERSNAP] Not finding known forum post
**Taken at**: https://pioneerapp.xyz/#/404
**Fields**:
- Houston, we have a problem.: Not finding known forum post
- Comment: This link is supposed to work: https://pioneerapp.xyz/#/forum/thread/70?post=282

SCREENSHOT
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/c02a63a8-2460-4078-8fa6-3a2d263aa794-annotated_d4cd384e-40fe-4fcd-8e68-cf5cef2f53ed.png?etag=eb53212bb7ab27a5b95bd354cc86b578)*

**Browser**: Firefox 109 (macOS Catalina)
**Screen size**: 5120x1440
**Browser size**: 1747x1153
**[Open #389 in Usersnap](https://app.usersnap.com/l/feedback/48f6fd48-eeb6-4203-b0e1-597b525b093f?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

### PR DESCRIPTION
**Pull request by IlyaSmiyukha**

### CODE REVIEW

**Comment by traumschule** [comment]
Welcome @IlyaSmiyukha please add to description: fixes #4170 #3659 #4189

**Comment by IlyaSmiyukha** [comment]
> Welcome @IlyaSmiyukha please add to description: fixes #3659
> 
> This has to be tested with a 12-digit balance.

Done

**Comment by chrlschwb** [comment]
There is no issue #4170.
And Issue #3659 is already fixed.
Please change title and description of PR to "Regression on WG History tab ", "fixes #4034", respectively.

**Comment by IlyaSmiyukha** [comment]
1. my fall, sorry it's a typo. Issue #4107 
2. Issuu #3659 still happened on production and dev, check the screenshot, please. 

Screenshot 2023-02-24 at 11 06 08

**Comment by traumschule** [comment]
Seems to work at 100% zoom and smaller window sizes. Thanks
Please reopen on another branch with correct title and issue in the description.

zoom

**Comment by IlyaSmiyukha** [comment]
Already did it. Pls, check [this one](https://github.com/Joystream/pioneer/pull/4203). And I'm not sure about the titles. If you will let me know how you usually name it will be great =)

**Pull request closed without merging**
