### PR TITLE
displayElectionRound without `round`

### PR DESCRIPTION
**Pull request by traumschule**
box is titled `ELECTION ROUND` and `0 round` is bad English

### CODE REVIEW

**Review by thesan — CHANGES_REQUESTED** [review]
Thank you for the pull request.

There is a `plural` function which is for example used in [packages/ui/src/common/components/statistics/BlockDurationStatistics.tsx](https://github.com/Joystream/pioneer/blob/02288f10f1266ffa79d52a9500f1743f6009b644/packages/ui/src/common/components/statistics/BlockDurationStatistics.tsx#L59). Using this function rather than removing the "round" would be more consistent with the rest of Pioneer design.

**Comment by dmtrjsg** [comment]
@traumschule pls review the fixes posted here > https://github.com/traumschule/pioneer/pull/1

**Comment by singulart** [comment]
Was there a ticket created to address this?

**Comment by singulart** [comment]
Looks good on prod env. 
Screenshot 2022-04-27 at 15 34 05

**Comment by traumschule** [comment]
relevant screenshot from https://pioneer-2-git-fork-traumschule-dev-joystream.vercel.app/#/election
round

**Pull request merged**
