### PR TITLE
2419 - Pass placeholder as props for SelectWorkingGroupOpening.

### PR DESCRIPTION
**Pull request by oleksanderkorn**
https://github.com/Joystream/pioneer/issues/2419

image

### CODE REVIEW

**Comment by oleksanderkorn** [comment]
@dmtrjsg i set the placeholder for Cancel Working Group Lead Opening to `Choose opening` instead `Choose application` i think this is correct. Let me know if you disagree.

**Comment by thesan** [comment]
@oleksanderkorn what we meant was that the placeholder of `<SelectWorkingGroupApplication />` should be `Choose application` but the placeholder for `<SelectWorkingGroupOpening />` in `CancelWorkingGroupLeadOpening` should probably be `Choose opening to cancel`

**Comment by oleksanderkorn** [comment]
@thesan  @dmtrjsg 
image

**Comment by thesan** [comment]
Screenshot from 2022-04-25 21-27-50

@oleksanderkorn yes I just realized it's not at all visible on the screenshot of the issue but the `SelectWorkingGroupApplication`'s placeholder is wrong too.

Because we had not realized that the placeholder were hardcoded, this issue was supposed to only be about "Fill WG lead proposal", that's why the proposed copy were "Choose opening to fill" for the opening selector and "Choose application" for the application selector.

**Comment by oleksanderkorn** [comment]
> Because we had not realized that the placeholder were hardcoded, this issue was supposed to only be about "Fill WG lead proposal", that's why the proposed copy were "Choose opening to fill" for the opening selector and "Choose application" for the application selector.

@thesan I have also made the placeholder for SelectWorkingGroupApplication a property and updated it to the correct text:
image

**Review by singulart — APPROVED** [review]

**Review by thesan — APPROVED** [review]
Thank you for the PR, and for the extra effort to expose the application select placeholder :pray:

**Pull request merged**
