### PR TITLE
📇 Rename leader to lead everywhere

### LINKED ISSUE #1098: Make Working Group Lead name consistent
Rename all the Working Group Leader instances to Working Group Lead.

If we use Leader in the code we also should use the domain name `Lead`.

### PR DESCRIPTION
**Pull request by DevNikita16**
Closes #1098

### CODE REVIEW

**Comment by DevNikita16** [comment]
@jodator Look carefully at every file 😆

**Comment by jodator** [comment]
> @jodator Look carefully at every single file 😆

I don't have to, we have CI that fails :P

**Comment by jodator** [comment]
@DevNikita16 I've checked every file :wink: and it looks OK. Could you check the branch conflict as well?

**Review by jodator — APPROVED** [review]
LGTM 👍 but the PR has conflicts

**Pull request merged**
