### PR TITLE
🔬 Add a decode helper command

### PR DESCRIPTION
**Pull request by thesan**
- #3525

This command requires two arguments:
- `-t`, `--type`: The expected type of the value to decode.
- `-v`, `--value`: The hash or the string representation of the `Uint8Array` to decode.

With `-t text` this command will simply decode encoded plaint text values. E.g:
```shell
> yarn workspace @joystream/pioneer run helpers decode -t text -v 0x4c6f72656d20697370756d
Lorem ispum
```

Otherwhise the type options should refer to a metadata class. It can be the name of the class:
```shell
> yarn workspace @joystream/pioneer run helpers decode -t CouncilCandidacyNoteMetadata -v 0x0a0a616...
CouncilCandidacyNoteMetadata {
  ...
}
```

Or it can be an alias:
```shell
> yarn workspace @joystream/pioneer run helpers decode -t candidacy -v 0x0a0a616...
CouncilCandidacyNoteMetadata {
  ...
}
```
The available aliases are: `post`, `opening`, `thread`, `bounty`, `candidacy`, `candidate`, `application`, `member`, and `membership`.

### CODE REVIEW

**Review by traumschule — APPROVED** [review]
Tested with [recent chain event data](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frpc.joystream.org#/explorer/query/0x3f22d17d69ff20bfccf40e1f9f4807c9eb1eb7baf7a02aa02255eddf9228ff24).

`pioneer$ yarn workspace @joystream/pioneer run helpers decode -t text -v 0x0a114a6f7973747265616d204368616e6e656c1226476f7420616e20696465613f2052656e74206f72206275792074686973206368616e6e656c2118012202656e`
> ^QJoystream Channel^R&Got an idea? Rent or buy this channel!^X"en

**Comment by thesan** [comment]
@traumschule 
> Tested with [recent chain event data](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frpc.joystream.org#/explorer/query/0x3f22d17d69ff20bfccf40e1f9f4807c9eb1eb7baf7a02aa02255eddf9228ff24).
> 
> `pioneer$ yarn workspace @joystream/pioneer run helpers decode -t text -v 0x0a114a6f7973747265616d204368616e6e656c1226476f7420616e20696465613f2052656e74206f72206275792074686973206368616e6e656c2118012202656e`
> 
> > ^QJoystream Channel^R&Got an idea? Rent or buy this channel!^X"en

That's interesting I wasn't expecting this byte to be somehow readable, but the correct command here is:
```shell
> yarn workspace @joystream/pioneer run helpers decode -t ChannelMetadata -v 0x0a114a6f7973747265616d204368616e6e656c1226476f7420616e20696465613f2052656e74206f72206275792074686973206368616e6e656c2118012202656e
ChannelMetadata {
  "title": "Joystream Channel",
  "description": "Got an idea? Rent or buy this channel!",
  "isPublic": true,
  "language": "en"
}
```
(I didn't create an alias for `ChannelMetadata` since Pioneer doesn't often deal with them).

Do you think the documentation should be made clearer ?

**Comment by traumschule** [comment]
> Do you think the documentation should be made clearer

I can't tell how many will use it and be able to guess correct type. :thinking: 
For me it's fine as is.

**Comment by thesan** [comment]
@traumschule thank you for the feedback. I added a link to [joystream/metadata-protobuf/doc/index.md](https://github.com/Joystream/joystream/blob/master/metadata-protobuf/doc/index.md) to help with the types.

**Pull request merged**
