### PR TITLE
Rwd/qa

### LINKED ISSUE #4628: Apply for a role: Form
Apply for a role: Form
768px, 1024px, 1440px

image
image
image

### PR DESCRIPTION
**Pull request by eshark9312**
closes #4628, #4629, #4630, #4631
- I did not update `Working Group/My Applications, My Roles` in mobile, because these pages can't be available without membership, same as the `My Profile` page is removed.
- And I did not follow the design for `Past proposals filter`, because the filter from the design is too tight so the dropdown is broken.
- IMO the issues with `Forum acivities` and `CK editor header` are not from responsive design. but the common issues, so I think it can be a separate `issue` from RWD.

### CODE REVIEW

**Comment by eshark9312** [comment]
@polikosi 
Some modals like `MemberDetail` should be shown even in mobile.
https://github.com/Joystream/pioneer/pull/4577#discussion_r1364221856

**Review by thesan — CHANGES_REQUESTED** [review]
@eshark9312 thank you for addressing these so quickly.

TBH it's a bit tricky to review this PR which mostly touches styles. The code looks good and you made some really good choices, however the [WGs table header row](https://dao-git-fork-eshark9312-rwd-qa-joystream.vercel.app/#/working-groups) is broken. Since this table serves as a homepage in Pioneer it really should be fixed:

 Screenshot from 2023-11-21 17-28-49

**Comment by polikosi** [comment]
Good job, but here are a few more minor issues

image

image

1440px
According to design voting result should be use Extra large variant.
image


### Announce candidacy
Sidebar should be set to 220px
image

### Announce candidacy: Reward account
Sidebar should be set to 220px
image

### Announce candidacy: Candidate profile
Sidebar should be set to 220px
image

**Comment by eshark9312** [comment]
@polikosi
According to the design, extra large variant of voting result have `total stake` and `revealed votes` column separate from the progress bar, but `my contributed votes` field is missed in the design, so I think we don't need to follow the design.

**Review by thesan — APPROVED** [review]
LGTM!

**Comment by polikosi** [comment]
@eshark9312 Hi, man. Here are a few new more minor issues)

1024px
can you do in 3 rows or something similar if possible  (more readable) 
image

It would be nice if it was centered 
image



1440, 1440+px
image
The same problem with "Vote" button
image


image

It would be nice if it was centered or on one side
image

**Comment by eshark9312** [comment]
@polikosi 
In the Announce Candidacy Modal, there is no enough space to implement the design when the `balance value` is too long.
IMO we can treat it with small variant of account selector.
And the last issue you mentioned is not a bug.

**Comment by polikosi** [comment]
@eshark9312 great job, thanks

**Pull request merged**
