### PR TITLE
My Voting Result was wrong!

### PR DESCRIPTION
**Pull request by GoldWolf115**
- #4250

### CODE REVIEW

**Review by chrlschwb — APPROVED** [review]

**Comment by chrlschwb** [comment]
@thesan can you please approve the workflow for GoldWolf? He's a new builder

**Review by thesan — APPROVED** [review]

**Review by thesan — COMMENTED** [review]
@GoldWolf115 the PR is good but please just run `yarn lint:fix` to fix the CI

**Comment by ivanturlakov** [comment]
In progress...
Tested on https://pioneer-2.vercel.app/#/election
Mainnet

Hanzo Hazashi(11 111joy)
0x2bc(33 333 + 77 777) from 2 wallets
leet_joy(55 555)

Screenshot 2023-10-25 at 14 59 18

**Comment by ivanturlakov** [comment]
Retested https://pioneer-2.vercel.app/#/election/past-elections/00000qjl
Screenshot 2023-11-01 at 14 31 31
Works as expected

Voted
for tester_(333+555=888joy) from 2 wallets
for tester(444joy)
Screenshot 2023-11-01 at 14 08 38
Votes Revealed
Screenshot 2023-11-01 at 14 20 14
Voting results
Screenshot 2023-11-01 at 14 25 41

**Pull request merged**
