### PR TITLE
♟ Use runtime IDs in Groups extrinsics

### LINKED ISSUE #781: Use runtime id as extrinsics params
We've assumed that the `id` in the query node will be the same as and `id` on the blockchain.

However, the objects related to Working Groups return `runtimeId` alongside `id`. That's because the items are indexed per working group, not globally. In other words a `Worker` with `id=forumWorkingGroup-1` belongs to forum working group and has runtime id `1`.

### PR DESCRIPTION
**Pull request by p-sad**
Closes #781

### CODE REVIEW

**Review by DevNikita16 — COMMENTED** [review]
Code looks fine!
But I thought this PR will fix Apply For Role Modal, but it's still not working

So should there be another ticket?

**Comment by jodator** [comment]
> So should there be another ticket?

Either new PR for #781 or let's fix all "runtimeId" in extrinsics where: `Worker`, `Opening` are used. I don't think that we have anything more to handle ATM.

**Comment by p-sad** [comment]
I completely missed Openings having runtimeIds as well. It shouldn't crash now.

**Review by DevNikita16 — APPROVED** [review]
👍✌️

**Pull request merged**
