### PR TITLE
Issue 2977

### PR DESCRIPTION
**Pull request by vrrayz**
Back button on openings now list to list page as requested from this [this issue](https://github.com/Joystream/pioneer/issues/2977)

### CODE REVIEW

**Review by traumschule — APPROVED** [review]
LGTM! Keep on it with #3768 if you want.

**Review by WRadoslaw — APPROVED** [review]
LGTM!

**Review by WRadoslaw — CHANGES_REQUESTED** [review]
Actually, I just noticed that this solution causes one bug. Problem is that when you go into opening details from a specific WG page, the back button will always transfer you to general openings instead of given WG ones.

Two cases have to be considered before pushing `customLink` to the stack:

- Whether `history.length` is bigger than 2 (if stack eq `1` then, the user clicks the link and get redirected, if stack eq `2` there is a possibility that the user opened a new tab in the browser and paste in the link
- Another possibility is that the user clicks on the URL to the openings list and then clicks on the given opening, in that case, checking for stack length will fail (stack length will equal `2`, but `goBack` should be invoked anyway), but we can check the current action on the history. I see that when you paste the URL or click on the link action will eq `POP` while if you navigate from Pioneer forward (Opening list -> Opening details) it will be `PUSH`

Integrating these two rules should do the work. WDYT?

**Comment by vrrayz** [comment]
> Actually, I just noticed that this solution causes one bug. Problem is that when you go into opening details from a specific WG page, the back button will always transfer you to general openings instead of given WG ones.
> 
> Two cases have to be considered before pushing `customLink` to the stack:
> 
> * Whether `history.length` is bigger than 2 (if stack eq `1` then, the user clicks the link and get redirected, if stack eq `2` there is a possibility that the user opened a new tab in the browser and paste in the link
> * Another possibility is that the user clicks on the URL to the openings list and then clicks on the given opening, in that case, checking for stack length will fail (stack length will equal `2`, but `goBack` should be invoked anyway), but we can check the current action on the history. I see that when you paste the URL or click on the link action will eq `POP` while if you navigate from Pioneer forward (Opening list -> Opening details) it will be `PUSH`
> 
> Integrating these two rules should do the work. WDYT?

I just made modifications based on your second suggestion. I think tracking the link action is all that's needed. I tested out for those cases you mentioned, and they work fine now

**Review by traumschule — APPROVED** [review]
lgtm! tested entering opening details from `/working-groups/openings` and `/working-groups/forum`.

**Review by oleksanderkorn — CHANGES_REQUESTED** [review]
Why does it have all the types changes here? I guess this can be done in a separate change if needed.

**Comment by traumschule** [comment]
You are right, didn't look at the code. @vrrayz resubmit the fix on a new branch.

**Pull request closed without merging**
