### PR TITLE
Fix: Handle empty vesting balances (My Accounts)

### PR DESCRIPTION
**Pull request by traumschule**
- Handles mysteriously empty BN values and adds a helper `sumBN` in `common/utils/bn` to sanely summarize a pair.
- Reverts the previous try.

## Rationale

Prior `My Accounts` was prone to `num.clone is not a function` on chain connection depending on balances input:
numclone

## Triage

With extra logging on-chain balances appear with extra `#bitLength: 128` property for `locked`, `transferable` and `locked` suggesting a similar code path.

### CODE REVIEW

**Comment by dmtrjsg** [comment]
@traumschule thank you for raising this!

Reviewed. Agreed to raise a PR pointed to Carthage branch and address this issue there. This one will get closed. @thesan will take care of it.

**Review by oleksanderkorn — APPROVED** [review]
LGTM!

**Review by thesan — CHANGES_REQUESTED** [review]
Please solve the conflicts

**Review by thesan — APPROVED** [review]
@traumschule it's nice that you removed the remaining references to gateway but please try to keep the PR focused on one goal. It would have been better to have a separate PR for this even if there is currently no issue about it.

**Comment by thesan** [comment]
@traumschule sorry it looks like the problem comes from #3813 never getting merged to `dev`. I should get a better git ui tool I keep on missing these since I switch IDE :facepalm:

**Pull request merged**
