### PR TITLE
🔮 Fix working-group/opening route

### PR DESCRIPTION
**Pull request by lucky-gru**
- [ ] #3268

**Task Description**:
  https://dao.joystream.org/#/working-groups/openings/operationsWorkingGroupAlpha-23
  would become 
  https://dao.joystream.org/#/working-groups/openings/Builders-23

### CODE REVIEW

**Comment by freakstatic** [comment]
LGTM!

**Comment by singulart** [comment]
Fixes https://github.com/Joystream/pioneer/issues/3268

**Comment by singulart** [comment]
@thesan Please review.

**Comment by thesan** [comment]
Sorry about the delay. The code looks good but I'm checking whether this is a desirable behavior

**Review by thesan — APPROVED** [review]
@lucky-gru @singulart 

Thank you for the contribution @lucky-gru, I'm approving the PR because the code looks good and the functionality works.

However #3268 is in fact about the Builders group and the Marketing group being swapped in the `working-groups/types/locks.ts` file (Builders should be Alpha and Marketing Gamma).

In addition rewriting opening urls to e.g `#/working-groups/openings/builders-23` is not a desirable functionality. Pioneer urls should stay consistent with the query nodes and the chain. For this reason I'm closing this PR.

**Comment by freakstatic** [comment]
@thesan the problem is that there is a big confusion with the groups names because Marketing should be actually Beta and HR Gama but I think it's a bit too late to revert this mistake now, so I suggested to @lucky-gru that would be better to completely hide this names from the user to avoid further confusion. 

Attaching a image from the beginning of the creation of the groups to prove what I'm mentioning
image

**Comment by freakstatic** [comment]
IMHO doesn't make sense to change the page groups title and content but keep the link the same...

**Comment by freakstatic** [comment]
@thesan but yes this doesn't fix what #3268 mentions about the builders...

so TL;DR every operations WG is wrong on pioneer according to the initial "plan" :facepalm:

**Comment by thesan** [comment]
@freakstatic thanks for clarifying this.

Apparently these aliases are also used [in the cli (with Beta -> HR, Gamma -> Marketing)](https://github.com/Joystream/joystream/blob/b7a8ed4cffdb23d41cf3618410a4a4a7dedf8d9a/cli/src/Api.ts#L67). So the url change would actually be a good thing for someone using the cli.

But `operationsWorkingGroup[Alpha|Beta|Gamma]` is what's shown by the QN and the runtime. So for someone coming from there to easily find pages on Pioneer, I think `#/working-groups/openings/operationsWorkingGroupBeta-0` should still be accessible somehow.
- Solution 1: `#/working-groups/openings/operationsWorkingGroupBeta-0` and `#/working-groups/openings/hr-0` both show the same page
- Solution 2: `#/working-groups/openings/operationsWorkingGroupBeta-0` redirect to `#/working-groups/openings/hr-0`

@freakstatic @dmtrjsg WDYT ?

**Comment by freakstatic** [comment]
> @freakstatic thanks for clarifying this.
> 
> Apparently these aliases are also used [in the cli (with Beta -> HR, Gamma -> Marketing)](https://github.com/Joystream/joystream/blob/b7a8ed4cffdb23d41cf3618410a4a4a7dedf8d9a/cli/src/Api.ts#L67). So the url change would actually be a good thing for someone using the cli.
> 
> But `operationsWorkingGroup[Alpha|Beta|Gamma]` is what's shown by the QN and the runtime. So for someone coming from there to easily find pages on Pioneer, I think `#/working-groups/openings/operationsWorkingGroupBeta-0` should still be accessible somehow.
> 
> * Solution 1: `#/working-groups/openings/operationsWorkingGroupBeta-0` and `#/working-groups/openings/hr-0` both show the same page
> * Solution 2: `#/working-groups/openings/operationsWorkingGroupBeta-0` redirect to `#/working-groups/openings/hr-0`
> 
> @freakstatic @dmtrjsg WDYT ?

thanks for understanding!
I prefer the Solution 2 but both seem fine by me.

It's interesting that this "error"/confusion spread to the whole project so if we could avoid showing this "raw names" would be great

**Comment by freakstatic** [comment]
I also found this that contradicts what I said previously about:
Beta -> Marketing
Gama -> HR

#3119 

so let's just agree that 
Beta -> HR
Gamma -> Marketing
like it's on pioneer right now

**Review by thesan — CHANGES_REQUESTED** [review]
@freakstatic, @lucky-gru  yes I agree whatever is the easiest to have both:
1. `#/working-groups/openings/[builder | hr | marketing]`
2. `#/working-groups/openings/operationsWorkingGroup[Alpha | Beta | Gamma]-$runtimeId`

to be somehow accessible is fine.

**Comment by dmtrjsg** [comment]
@freakstatic hey buddy, this one seem to be idle for quite a long time, would you be open to bringing this home? Seems like you're quite involved on having this merged.. let us know ;)

**Comment by freakstatic** [comment]
> @freakstatic hey buddy, this one seem to be idle for quite a long time, would you be open to bringing this home? Seems like you're quite involved on having this merged.. let us know ;)

yeah you are right is one is idle for too long now... I'm gonna check with @lucky-gru to see if he is available if not I'm gonna take this one myself and finish it

**Comment by dmtrjsg** [comment]
@freakstatic qq will you have a chance to revisit this one .. not time critical but would be still good to bring it over the line at some point. 

tytyty

**Comment by traumschule** [comment]
> whatever is the easiest to have both:
> 1. `#/working-groups/openings/[builder | hr | marketing]`
> 2. `#/working-groups/openings/operationsWorkingGroup[Alpha | Beta | Gamma]-$runtimeId`
> to be somehow accessible is fine.

@thesan This looks done to me, please confirm.

opneing-routes

**Comment by thesan** [comment]
@traumschule 

> @thesan This looks done to me, please confirm.

Not yet. On this branch [#/working-groups/openings/marketing-2](https://dao-git-fork-lucky-gru-fix-working-group-openi-92a30b-joystream.vercel.app/#/working-groups/openings/marketing-2) is accessible and is the default which is good. But this route is not: [#/working-groups/openings/operationsWorkingGroupGamma-2](https://dao-git-fork-lucky-gru-fix-working-group-openi-92a30b-joystream.vercel.app/#/working-groups/openings/operationsWorkingGroupGamma-2)

I detailed the reason for why both should be reachable [here](https://github.com/Joystream/pioneer/pull/3399#issuecomment-1203765636)

> But `operationsWorkingGroup[Alpha|Beta|Gamma]` is what's shown by the QN and the runtime. So for someone coming from there to easily find pages on Pioneer, I think `#/working-groups/openings/operationsWorkingGroupBeta-0` should still be accessible somehow.
    - Solution 1: `#/working-groups/openings/operationsWorkingGroupBeta-0` and `#/working-groups/openings/hr-0` both show the same page
    - Solution 2: `#/working-groups/openings/operationsWorkingGroupBeta-0` redirect to `#/working-groups/openings/hr-0`

**Comment by traumschule** [comment]
Fixed in #3727

openingRoute

**Pull request closed without merging**
