### PR TITLE
🔐 Show transaction error modal when Polkadot extension is closed

### LINKED ISSUE #1482: Show transaction error modal when closing Polkadot extension

### PR DESCRIPTION
**Pull request by DevNikita16**
Closes #1482

### CODE REVIEW

**Comment by DevNikita16** [comment]
Wondering how commit from previous PR appeared here

**Comment by DevNikita16** [comment]
@jodator also what should be instead of `any` for `onTransactionError` type. I was playing with types, but haven't succeeded

**Review by jodator — COMMENTED** [review]
It would be actually quite good to show a different error message. I think that we need to have a different event for that case.

If you do this now, we could introduce better error handling.

**Comment by DevNikita16** [comment]
> It would be actually quite good to show a different error message. I think that we need to have a different event for that case.
> 
> If you do this now, we could introduce better error handling.

I'd like to dive into my current [issue](https://github.com/Joystream/pioneer/issues/1465). So if we could just create issue for later would be awesome 🤩

**Comment by jodator** [comment]
> @jodator I'd like to dive into my current [issue](https://github.com/Joystream/pioneer/issues/1465). So if we could just create issue for later would be awesome 🤩

OK, so please create an issue for that.

**Pull request merged**
