### PR TITLE
Rwd/address QA issue #4609

### LINKED ISSUE #4609: RWD Bugs
Screenshot 2023-10-28 at 14 01 20
Screenshot 2023-10-28 at 13 53 20
Screenshot 2023-10-28 at 13 50 21

Screenshot 2023-10-27 at 21 42 12
Screenshot 2023-10-27 at 21 35 36

Perhaps here we can hide the second column so that the third column is readable
Screenshot 2023-10-27 at 22 21 28

### PR DESCRIPTION
**Pull request by eshark9312**
closes #4609

### CODE REVIEW

**Comment by chrlschwb** [comment]
image

**Review by chrlschwb — APPROVED** [review]

**Review by thesan — CHANGES_REQUESTED** [review]
Nice work on fixing everything else but the empty proposal state is still not centered:

image

You can see it on e.g:  https://dao-git-fork-eshark9312-rwd-address-qa-issue-4609-joystream.vercel.app/#/proposals/current?network-config=https://atlas-dev.joystream.org/network/config.json

**Review by thesan — CHANGES_REQUESTED** [review]
The setting page is not centered anymore:
image

Also IMO the activities on the council and proposals page are too narrow:
image

Since the main content already has a padding on the right side, I don't think all these nested padding-right are necessary anymore

**Comment by eshark9312** [comment]
@thesan 
I updated.

**Comment by polikosi** [comment]
> @polikosi I addressed the issues requested from @thesan, please review the changes.

✅Proposal page centered
image

@eshark9312 WDYT?
⚠️in my opinion, the settings page does not look centered enough. 
image
⚠️the settings page does not look centered at all if I select another screen 
image

✅proposal page
image
✅council page
image

**Comment by eshark9312** [comment]
@polikosi 
Please check the design for settings page.
https://www.figma.com/file/EaObQEN95O0IWjSVTUQ5NN/Pioneer-RWD?type=design&node-id=5-6470&mode=dev

**Review by thesan — APPROVED** [review]
Once again, great work!

**Comment by thesan** [comment]
@polikosi @chrlschwb I'm merging this but if needed the QA can be continued on https://dao-git-responsive-joystream.vercel.app/

**Pull request merged**
