### PR TITLE
issue #3316 fixed

### PR DESCRIPTION
**Pull request by chrlschwb**
It was a problem of Thread Status.
I have changed the "ThreadStatusModerated" to "ThreadStatusRemoved" in the hooks.

### CODE REVIEW

**Comment by traumschule** [comment]
Thanks @chrlschwb! Looks like this would fix #3316 but I wonder if it also unhides threads flagged `ThreadStatusModerated`?

**Comment by chrlschwb** [comment]
Hello.
Yes, the threads ThreadStatusModerated would unhide.
Let me know if it needs fixing.

**Review by traumschule — CHANGES_REQUESTED** [review]
Yes, both ThreadStatusRemoved and ThreadStatusModerated need to be hidden.

**Comment by traumschule** [comment]
This is obsolete, see https://github.com/Joystream/pioneer/issues/3153#issuecomment-1294003934

**Comment by chrlschwb** [comment]
Hello, l1dev.
What is this message for?

**Comment by traumschule** [comment]
It means JSG will rework the forum on their own for now.

**Pull request closed without merging**
