### PR TITLE
🙈 fix: Delete and Edit buttons are shown on removed thread pages #3266

### PR DESCRIPTION
**Pull request by gyroflaw**
Fixes https://github.com/Joystream/pioneer/issues/3266

### CODE REVIEW

**Review by thesan — CHANGES_REQUESTED** [review]
@gyroflaw nice fix. But the original issue is about having the edit/delete button on already deleted threads.

E.g:
With `chevdor` (the member bound to Alice), I created and delete a thread here: https://dao-git-fork-gyroflaw-fix-forum-thread-remove-154e70-joystream.vercel.app/#/forum/thread/1707

If you pick `chevdor` on this thread you will see that the edit and delete buttons still show, despite the thread being deleted (deleted post can't be edited nor deleted again).

**Comment by gyroflaw** [comment]
> 

I am not able to find any `edit` or `delete` buttons.
image
Could you please share screenshot?

**Comment by thesan** [comment]
@gyroflaw sorry I had completely missed your reply. Here's a screenshot:

**Review by thesan — APPROVED** [review]
Thanks! Nice work :tophat:

**Pull request merged**
