### PR TITLE
858 - Add option to filter members by isCouncil

### PR DESCRIPTION
**Pull request by oleksanderkorn**
GH Issue: https://github.com/Joystream/pioneer/issues/858

NB: Using property `isCouncilMember_eq` property in graphQL query gives bad request error:
```
message: "Variable \"$where\" got invalid value { isCouncilMember_eq: true }; Field \"isCouncilMember_eq\" is not defined by type MembershipWhereInput. Did you mean isFoundingMember_eq or isFoundingMember_in?"
```

### CODE REVIEW

**Comment by jodator** [comment]
@oleksanderkorn Thank you for the PR. I will try to fix the test status not reporting today.

As for the PR:

*   [x] The filtering for council members works
*   [ ] The filtering for non-council member does not work (show all workers)
*   [ ] It would be nice to fetch the `isCouncil` [flag](https://github.com/Joystream/pioneer/blob/75dc82f3ea55a29e462731323bb898348ebb039d/packages/ui/src/memberships/queries/members.graphql#L14-L15) and [expose it](https://github.com/Joystream/pioneer/blob/75dc82f3ea55a29e462731323bb898348ebb039d/packages/ui/src/memberships/types/casting.ts#L15-L16) with the `Member` data...
*   [ ] ...and use it to [display](https://github.com/Joystream/pioneer/blob/b8c03e1386638c0cbf18b889856f761967632e71/packages/ui/src/memberships/components/MemberListItem/Member.tsx#L30) `Council` status

The current `useIsCouncilMember()` hook is temporary since the testnet does not return the `isCouncil` flag `yet`.

**Comment by jodator** [comment]
@oleksanderkorn I hope that after merging #1709 the GH Action will build on your changes.

**Comment by oleksanderkorn** [comment]
@jodator added `The filtering for non-council member does not work (show all workers)`

**Comment by jodator** [comment]
Thanks! I see that the PR workflow was properly updated. I've just approved the CI run so it should go smoothly from now.

**Comment by oleksanderkorn** [comment]
@jodator can you reapprove, previous run failed with linting issues.

**Comment by oleksanderkorn** [comment]
@jodator ci built has failed, seems to be not related to my changes, maybe flaky test?

**Comment by jodator** [comment]
> @jodator ci built has failed, seems to be not related to my changes, maybe flaky test?

I'm sorry, but I didn't manage to check this today. I will check the test tomorrow morning.

**Comment by jodator** [comment]
The issue with that test might be resolved by #1718.

**Comment by oleksanderkorn** [comment]
@jodator rebased on the latest main branch, ci passed :)

**Comment by jodator** [comment]
@oleksanderkorn Thanks! I see that this should work fine now, but we need to postpone the merge until this PR gets merged: Joystream/joystream#2672 Otherwise whole app stop being usable with the current testnet. Unfortunately, the current testnet does not have the council schema updated yet.

**Comment by jodator** [comment]
If Ci will pass the PR is going to be merged :tada:

**Comment by jodator** [comment]
Confirmed that this works on the current testnet. Thanks!

**Pull request merged**
