### PR TITLE
AddNewProposal modal: Move up `Stake` and `Constitutionality` (#4044)

### PR DESCRIPTION
**Pull request by traumschule**
#4044

### CODE REVIEW

**Comment by traumschule** [comment]
@mochet tested in extra small window. good enough?

addprop

I agree space could be saved by not breaking lines for quorums for example.

**Comment by chrlschwb** [comment]
@thesan 
through QA test, it has been concluded to move on with PR 4050 and discard PR 4073

**Review by freakstatic — APPROVED** [review]
LGTM!

**Review by thesan — APPROVED** [review]
:+1:

**Pull request merged**
