### PR TITLE
Inconsistent number of digits fix (#3990)

### PR DESCRIPTION
**Pull request by chrlschwb**
#3990

### CODE REVIEW

**Review by traumschule — APPROVED** [review]

**Comment by traumschule** [comment]
> Solution proposed would possible make it more confusing as decimals and comma separators would start to get mixed up.

Do you think there's big chance for confusion? All numbers align perfectly now.
accounts

**Comment by traumschule** [comment]
@chrlschwb please check the test fails now
```
 | FAIL test/proposals/modals/AddNewProposalModal.test.tsx (383.75 s)
 |   ● UI: AddNewProposalModal › Stepper modal › Authorize › Staking account not bound nor staking candidate › Bind account step
 |     expect(received).toBe(expected) // Object.is equality
 |     Expected: "42"
 |     Received: "42.0"
```

**Comment by chrlschwb** [comment]
CI / test is failing because the expected output is different from received output.
Since this PR touches common files like
packages/ui/src/common/components/typography/TokenValue.tsx
packages/ui/src/common/model/formatters.ts

It would require to change the test files themselves.

**Comment by traumschule** [comment]
Never mind.

**Pull request closed without merging**
