### PR TITLE
🎳 Whole WG item is clickable link

### LINKED ISSUE #1287: WG items as clickable items

### LINKED ISSUE #1292: Openings item as clickable item

### LINKED ISSUE #1293: Roles from 'My roles' as clickable items

### LINKED ISSUE #1294: Correctly use popper for ContextMenu

### LINKED ISSUE #1295: Account item from 'My accounts' as clickable item

### LINKED ISSUE #1296: Member item from 'Memberships' as clickable item

### LINKED ISSUE #1313: Member item in Members as clickable item

### PR DESCRIPTION
**Pull request by ClumsyVlad**
Closes #1287 
Closes #1292  
Closes #1293  
Closes #1294 
Closes #1295  
Closes #1296 
Closes #1313

### CODE REVIEW

**Comment by jodator** [comment]
To check:

*   [ ] Member item in the members list

**Review by p-sad — COMMENTED** [review]
Looks good; there's one thing that I would change (below).
I see that members list items (`/members`) don't follow suit, but that can be done as a follow-up

**Comment by jodator** [comment]
> ```
> * Member item in the members list
> ```

@ClumsyVlad I might not been clear enough. If you go to the members section (the one with all of the members) there's a double border in the list.

**Comment by jodator** [comment]
> ```
> * Member item in the members list
> ```

@ClumsyVlad I might not been clear enough. If you go to the members section (the one with all of the members) there's a double border in the list.

**Review by jodator — APPROVED** [review]
Thanks!

**Pull request merged**
