### PR TITLE
Fix bounties modals not resizing with windows size

### LINKED ISSUE #3201: Incorrect window size on the "submit work" page
## Context

Incorrect window size

the bottom of the modal is showing beneath screen fold
Screenshot_102

## Scope

- [ ] Change the styling on the modal to support good centering and sizing
⚠️ pls do together with - https://github.com/joystream/pioneer/issues/3025
and - #2976

### PR DESCRIPTION
**Pull request by freakstatic**
Fixes #3201, #2976 and #3025

### CODE REVIEW

**Comment by singulart** [comment]
@WRadoslaw @thesan Please expedite the review. CC: @dmtrjsg

**Comment by WRadoslaw** [comment]
Hey Freakstatic! Nice to see your PR again! I think we should approach this issue globally with only changes in modals CSS.

Here is screenshot with changes that should be enough to force correct behaviour.

This media query was just me playing around you can remove or leave it (is should remove bottom padding on smaller devices), but feel free to extend this solution with extra media to remove or shrink padding on top of modal for smaller devices (inside this switch `switch (modalHeight)`).
image

Please let me know it you have any questions or sugestions :)

**Comment by WRadoslaw** [comment]
> > 
> 
> Hi @WRadoslaw! Thanks, your solution is simpler so I agree we should go with that! About the paddings maybe we can just do:
> 
> ```
> padding-bottom: ${({ modalHeight }) => {
>     switch (modalHeight) {
>       case 's':
>         return '0px'
>       case 'm':
>         return '60px'
>       case 'l':
>         return '44px'
>       case 'xl':
>         return '40px'
>     }
>   }};
> ```
> 
> What do you think? I force-pushed a mix of your suggested solution and this padding code

`max-height: calc(100%-128px)` is making padding bottom appearance already, so there is no need for extra bottom padding. I was thinking about removing top padding that is currently defined in `Modal Glass` on smaller screens, so we don't waste that much of space that we don't have. 

Here is a snippet: 
```
padding-top: ${({ modalHeight }) => {
    switch (modalHeight) {
      case 's':
        return '0px'
      case 'm':
        return '60px'
      case 'l':
        return '44px'
      case 'xl':
        return '40px'
    }
  }};
```

**Comment by freakstatic** [comment]
> > > 
> > 
> > 
> > Hi @WRadoslaw! Thanks, your solution is simpler so I agree we should go with that! About the paddings maybe we can just do:
> > ```
> > padding-bottom: ${({ modalHeight }) => {
> >     switch (modalHeight) {
> >       case 's':
> >         return '0px'
> >       case 'm':
> >         return '60px'
> >       case 'l':
> >         return '44px'
> >       case 'xl':
> >         return '40px'
> >     }
> >   }};
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > What do you think? I force-pushed a mix of your suggested solution and this padding code
> 
> `max-height: calc(100%-128px)` is making padding bottom appearance already, so there is no need for extra bottom padding. I was thinking about removing top padding that is currently defined in `Modal Glass` on smaller screens, so we don't waste that much of space that we don't have.
> 
> Here is a snippet:
> 
> ```
> padding-top: ${({ modalHeight }) => {
>     switch (modalHeight) {
>       case 's':
>         return '0px'
>       case 'm':
>         return '60px'
>       case 'l':
>         return '44px'
>       case 'xl':
>         return '40px'
>     }
>   }};
> ```

So should I add a media query on the code reference by that snippet or did you paste the wrong thing? :thinking:

**Comment by freakstatic** [comment]
something like 
```
@media only screen and (max-height: 700px) {
    padding-top: 0px;
  }
```

**Comment by freakstatic** [comment]
something like 
```
@media only screen and (max-height: 700px) {
    padding-top: 0px;
  }
```

**Review by WRadoslaw — APPROVED** [review]

**Comment by singulart** [comment]
@thesan Can you please merge the PR? It was approved by reviewer @WRadoslaw. Thank you!

**Comment by WRadoslaw** [comment]
I'll merge it as soon as tests will pass

**Comment by singulart** [comment]
@WRadoslaw I think all checks are green :)

**Pull request merged**
