### PR TITLE
🏴 Removing black loading modal

### PR DESCRIPTION
**Pull request by WRadoslaw**
- #3508

### CODE REVIEW

**Comment by dmtrjsg** [comment]
Agreed to replace this component with the updated spinner everywhere: https://pioneer-2-storybook-git-fix-kill-black-spinner-joystream.vercel.app/?path=/story/common-loading--loading-component

Also leave the opportunity to add the text if needed. For now will not needed anywhere apart from loading avatar on new member creation flow.

**Review by thesan — CHANGES_REQUESTED** [review]
Nice refactor :raised_hands: 

I think the WaitModal, SearchProcess and their stories/icons should be removed too to simplify the codebase.

**Comment by WRadoslaw** [comment]
@thesan As SearchProcess can be removed, WaitModal is still utilized on the Onboarding modal to indicate that faucet is processing the request (as it's a normal POST request, not a tx we don't use bottom tx modal). If we wanna remove it we need to find an alternative.

**Review by thesan — APPROVED** [review]
Right! It makes sense for the Onboarding modal

**Pull request merged**
