### PR TITLE
Add Tooltips To Staking In Election

### PR DESCRIPTION
**Pull request by Palllke2015**
https://dao.joystream.org/#/bounty/preview/43
tooltips

### CODE REVIEW

**Review by stepien4soft — APPROVED** [review]

**Comment by stepien4soft** [comment]
@Palllke2015 Thanks for that!

**Comment by freakstatic** [comment]
@Palllke2015 I think you wanted to change the 
`packages/ui/src/council/modals/VoteForCouncil/VoteForCouncilFormModal.tsx` and not the `packages/ui/src/memberships/modals/BuyMembershipModal/BuyMembershipFormModal.tsx`

**Review by stepien4soft — CHANGES_REQUESTED** [review]
Tolltips should be added in different files. Thanks @freakstatic

**Comment by freakstatic** [comment]
LGTM!
image
image

**Review by stepien4soft — APPROVED** [review]

**Review by WRadoslaw — APPROVED** [review]

**Comment by freakstatic** [comment]
Fixes #2303

**Comment by thesan** [comment]
Closing and reopening for the CI

**Pull request closed without merging**
