### PR TITLE
Fix Candidates Card "Staked" copy

### PR DESCRIPTION
**Pull request by BeardKoda**
#2795 
- My stake on candidate stake to be renamed to "Staked"

### CODE REVIEW

**Comment by freakstatic** [comment]
Hi @BeardKoda!
Thanks for the PR, LGTM! :+1:

**Comment by singulart** [comment]
@thesan This is still needs to be reviewed, thank you!

**Review by WRadoslaw — APPROVED** [review]
Thanks! 👏

**Comment by thesan** [comment]
@singulart, @BeardKoda sorry I've been really late on the PR review lately.
@BeardKoda please could you change the failing test in `test/council/pages/Election.test.tsx`:
From:  `expect(queryAllByText(/my stake/i).length).toBe(1)`
To: `expect(queryAllByText(/Staked/i).length).toBe(1)`

**Pull request merged**
